const APP_BASE_PATH = "http://localhost:3000";

module.exports = {
  "Landing Page tests": browser => {
    browser
      .url(APP_BASE_PATH)
      .waitForElementVisible("body", 5000)
      .assert.urlEquals(`${APP_BASE_PATH}/`)
      .pause(2000)
      .assert.visible(".accounts-dropdown")
      .pause(3000)
      // .assert.visible(".btn.btn-default.variant-button")
      // .click(".btn.btn-default.variant-button")
      // .pause(3000)
      .assert.visible(".carousel-section")
      .pause(3000)
      .assert.visible(".btn-shop")
      .pause(3000)
      .assert.visible(".about-us-section")
      .pause(3000)
      .assert.visible(".fa-phone")
      .pause(3000)
      .assert.visible(".top-categories")
      .pause(3000)
      .assert.visible(".fa-phone")
      .pause(3000)
      .assert.visible(".category-catalog")
      .pause(3000)
      .assert.visible(".b-image")
      .pause(3000)
      .assert.visible(".fa-comments")
      .pause(3000)
      .assert.visible(".top-stores")
      .pause(3000)
      .assert.visible(".shop-card")
      .pause(3000)
      .assert.visible(".reviews-explore")
      .pause(3000)
      .assert.visible(".reviews-section")
      .pause(3000)
      .assert.visible(".rs-header")
      .pause(3000)
      .assert.visible(".review-box")
      .pause(3000)
      .assert.visible(".product-details")
      .pause(3000)
      .assert.visible(".p-details")
      .pause(3000)
      .assert.visible(".panel")
      .pause(3000)
      .assert.visible(".footer")
      .pause(3000)
      .assert.visible(".footer-one-header")
      .pause(3000)
      .assert.visible(".social-icons-section")
      .pause(3000)
      .assert.visible(".fa-facebook")
      .pause(3000)
      .assert.visible(".fa-twitter")
      .pause(3000)
      .assert.visible(".fa-linkedin")
      .pause(3000)
      .assert.visible(".fa-google")
      .pause(3000);
  }
};
