/* global module */
const APP_BASE_PATH = "http://localhost:3000";

module.exports = {
  "An admin should be able to cancel an order": browser => {
    browser
      .url(APP_BASE_PATH)
      .waitForElementVisible("body", 5000)
      .assert.urlEquals(`${APP_BASE_PATH}/`)
      .pause(2000)
      .assert.visible("body")
      .assert.visible("span")
      .assert.visible(".accounts-dropdown")
      .click(".accounts-dropdown")
      .setValue(".email-edit-input", "admin@localhost")
      .setValue(".password-edit-input", "r3@cti0n")
      .click(".rui.btn.btn-primary.solid.btn-block")
      .pause(3000)
      // .assert.visible(".btn.btn-default.variant-button")
      // .click(".btn.btn-default.variant-button")
      // .pause(3000)
      .assert.visible(".input-group-addon.add-to-cart-text.js-add-to-cart")
      .click(".input-group-addon.add-to-cart-text.js-add-to-cart")
      .pause(3000)
      .assert.visible(".rui.btn.btn-success.solid.btn-lg.btn-block")
      .click(".rui.btn.btn-success.solid.btn-lg.btn-block")
      .pause(3000)
      .assert.visible(".list-group-item")
      .click(".list-group-item")
      .pause(3000)
      .assert.visible("input[name=payerName]")
      .setValue("input[name=payerName]", "Idrees Ibraheem")
      .pause(2000)
      .assert.visible("input[name=cardNumber]")
      .setValue("input[name=cardNumber]", "5242890899515853")
      .pause(2000)
      .assert.visible("select[name=expireMonth]")
      .click("select[name=expireMonth]")
      .pause(2000)
      .assert.visible("select[name=expireMonth] option[value='4']")
      .click("select[name=expireMonth] option[value='4']")
      .pause(2000)
      .assert.visible("select[name=expireYear]")
      .click("select[name=expireYear]")
      .pause(2000)
      .assert.visible("select[name=expireYear] option[value='2019']")
      .click("select[name=expireYear] option[value='2019']")
      .pause(3000)
      .assert.visible("input[name=cvv]")
      .setValue("input[name=cvv]", "144")
      .pause(3000)
      .assert.visible(".rui.btn.btn-lg.btn-cta.btn-block.btn-complete-order")
      .click(".rui.btn.btn-lg.btn-cta.btn-block.btn-complete-order")
      // .pause(3000)
      // .assert.visible(".rui.btn.btn-lg.btn-cta.btn-block.btn-complete-order");
      .pause(3000)
      .assert.visible(".btn-rate-shop");
  }
};
